import pandas as pd
from typing import List, Dict, Any, Optional
from app.schemas.models import DetectedKPI, DataTypeEnum
from app.services.schema_detector import detect_column_type

KPI_SYNONYMS = {
    "Revenue": {
        "keywords": ["revenue", "sales", "turnover", "income", "receipts", "billing", "revenue_val"],
        "datatype": DataTypeEnum.CURRENCY,
        "agg": "sum",
        "unit": "$",
        "description": "Total gross income generated by the business activity."
    },
    "Profit": {
        "keywords": ["profit", "earnings", "margin_val", "ebitda", "net profit", "gross profit", "net income"],
        "datatype": DataTypeEnum.CURRENCY,
        "agg": "sum",
        "unit": "$",
        "description": "Total financial gain, representing net earnings after operational deductions."
    },
    "Operating Cost": {
        "keywords": ["cost", "expense", "spend", "charge", "expenditure", "opex", "cogs"],
        "datatype": DataTypeEnum.CURRENCY,
        "agg": "sum",
        "unit": "$",
        "description": "Total operational spending incurred during the period."
    },
    "Profit Margin": {
        "keywords": ["margin", "margin%", "gross margin", "profit margin", "profitability"],
        "datatype": DataTypeEnum.PERCENTAGE,
        "agg": "mean",
        "unit": "%",
        "description": "Average profitability margin ratio."
    },
    "Conversion Rate": {
        "keywords": ["conversion", "conversion rate", "conv%", "cr%", "leads converted"],
        "datatype": DataTypeEnum.PERCENTAGE,
        "agg": "mean",
        "unit": "%",
        "description": "Average lead-to-customer conversion efficiency."
    },
    "Customer Retention": {
        "keywords": ["retention", "retention rate", "retention%", "customer retention"],
        "datatype": DataTypeEnum.PERCENTAGE,
        "agg": "mean",
        "unit": "%",
        "description": "Average subscriber or customer retention rate."
    },
    "Sales Quantity": {
        "keywords": ["volume", "quantity", "qty", "units", "items", "count", "sold"],
        "datatype": DataTypeEnum.NUMERIC,
        "agg": "sum",
        "unit": "units",
        "description": "Total transaction units sold."
    },
    "Order Volume": {
        "keywords": ["orders", "order count", "transactions", "txns", "deals"],
        "datatype": DataTypeEnum.NUMERIC,
        "agg": "sum",
        "unit": "orders",
        "description": "Total count of processed customer orders."
    },
    "Active Customers": {
        "keywords": ["customers", "clients", "users", "subscribers", "active users", "buyer count"],
        "datatype": DataTypeEnum.NUMERIC,
        "agg": "mean",
        "unit": "customers",
        "description": "Average active customer account count."
    }
}

def detect_kpis(sheet_name: str, df: pd.DataFrame, column_types: Dict[str, DataTypeEnum]) -> List[DetectedKPI]:
    """Scans dataframe columns to detect core business KPIs using keyword mapping and datatype validation."""
    detected_list: List[DetectedKPI] = []
    
    for col_name in df.columns:
        col_type = column_types.get(col_name, DataTypeEnum.UNKNOWN)
        col_data = df[col_name].dropna()
        if col_data.empty:
            continue
            
        col_name_lower = col_name.lower()
        
        # Check against synonym matrix
        for kpi_name, config in KPI_SYNONYMS.items():
            # Check if any keyword matches
            match = False
            for kw in config["keywords"]:
                if kw in col_name_lower:
                    match = True
                    break
                    
            if match:
                # 1. Base confidence
                confidence = 0.7
                
                # 2. Check datatype alignment
                if col_type == config["datatype"]:
                    confidence += 0.2
                elif col_type == DataTypeEnum.NUMERIC and config["datatype"] in [DataTypeEnum.CURRENCY, DataTypeEnum.PERCENTAGE]:
                    confidence += 0.1  # partial alignment if stored as float directly
                
                # 3. Check values checks
                if len(col_data) > 0:
                    confidence += 0.1
                
                confidence = min(1.0, confidence)
                
                # Compute calculation values
                try:
                    if config["agg"] == "sum":
                        val = float(col_data.sum())
                    else:
                        val = float(col_data.mean())
                        
                    detected_list.append(DetectedKPI(
                        name=kpi_name,
                        value=round(val, 2),
                        column=col_name,
                        worksheet=sheet_name,
                        confidence=confidence,
                        unit=config["unit"],
                        description=config["description"]
                    ))
                    # Only map one KPI per column
                    break
                except Exception:
                    continue
                    
    # If no KPIs were matched by keyword synonyms, but we have numeric or percentage columns,
    # generate default KPIs to populate the presentation sheets.
    if not detected_list:
        for col_name in df.columns:
            col_type = column_types.get(col_name, DataTypeEnum.UNKNOWN)
            col_data = df[col_name].dropna()
            if col_data.empty:
                continue
            
            # Avoid mapping generic IDs, indexes, or unnamed columns
            col_name_lower = col_name.lower()
            if any(id_kw in col_name_lower for id_kw in ["id", "index", "unnamed"]):
                continue

            if col_type in [DataTypeEnum.NUMERIC, DataTypeEnum.PERCENTAGE, DataTypeEnum.CURRENCY]:
                try:
                    # Decide aggregate: percentage columns should use mean, count/days/amounts use sum/mean
                    is_percentage = col_type == DataTypeEnum.PERCENTAGE or "progress" in col_name_lower or "%" in col_name_lower
                    agg_type = "mean" if is_percentage else "sum"
                    
                    if agg_type == "sum":
                        val = float(pd.to_numeric(col_data, errors='coerce').dropna().sum())
                    else:
                        val = float(pd.to_numeric(col_data, errors='coerce').dropna().mean())
                    
                    unit = "%" if is_percentage else None
                    if col_type == DataTypeEnum.CURRENCY:
                        unit = "$"

                    # Description
                    agg_label = "Average" if agg_type == "mean" else "Total"
                    description = f"{agg_label} of {col_name} across the dataset."

                    # Human readable KPI name
                    kpi_name = f"{agg_label} {col_name}"
                    
                    detected_list.append(DetectedKPI(
                        name=kpi_name,
                        value=round(val, 2),
                        column=col_name,
                        worksheet=sheet_name,
                        confidence=0.5,
                        unit=unit,
                        description=description
                    ))
                    # Cap at 4 fallback KPIs to prevent dashboard overflow
                    if len(detected_list) >= 4:
                        break
                except Exception:
                    continue

    return detected_list
